---
# tasks file for server-access

- set_fact:
   random_number: "{{ 100 | random }}"
  run_once: yes

- include_tasks: user_access_verify.yml
  #when: ansible_os_family == "RedHat"

#- include_tasks: python_verify.yml
  #when: ansible_os_family == "RedHat"

#- include_tasks: user_analyze.yml
  #when: ansible_os_family == "RedHat"  

