---
# tasks file for server-access

- name: "Verify Access status of Inventory Hostnames"
  raw: "{{ get_ip }} && id -Gn && echo {{ group_names }}" 
  no_log: true
  ignore_errors: yes
  register: servergroups

- name: "DEBUG: Verify Access status of Inventory Hostnames"
  debug:
    msg: "{{ servergroups }}"

- name: "Output Information to {{ jenkinsws }}OUT_{{ date_time }}_{{ random_number }}.csv"
  lineinfile:
    dest: "{{ jenkinsws }}/OUT_{{ date_time }}_{{ random_number }}.csv"
    line: "{{ inventory_hostname }},{{ servergroups.stdout_lines | regex_replace('\\[|u(?!sers)|\\]', '') }}"
    create: true
    state: present
  delegate_to: localhost

- name: Remove single quotes
  replace:
    path: "{{ jenkinsws }}/OUT_{{ date_time }}_{{ random_number }}.csv"
    regexp: "'"
    replace: ""
  delegate_to: localhost

- name: Replace comma-space with comma.
  replace:
    path: "{{ jenkinsws }}/OUT_{{ date_time }}_{{ random_number }}.csv"
    regexp: ", "
    replace: ","
  delegate_to: localhost